### ISSUE TITLE
Sort log output

### ISSUE THREAD

**Issue by nils-braun** [dotcs/worklog#7]
Thanks for this great tool @dotcs !

I was wondering, do you think it makes sense to sort the log on the start/stop time?
e.g. here: https://github.com/dotcs/worklog/blob/develop/worklog/log.py#L107

**Comment by dotcs** [comment]
Thanks for the kind words @nils-braun! :+1: I'm glad that you like it.

So please help me to understand what you mean with sorted? For each entry in the "database" file two timestamps are stored. The first one is about the time when the entry was written, the second is about the "log date".

See this example:

```bash
rm -rf ~/.worklog                       
wl commit stop   # current time 2020-08-31T19:07:44+02:00
wl commit start -t 08:05
cat ~/.worklog          
2020-08-31 19:07:44+02:00|2020-08-31 19:07:44+02:00|session|stop|
2020-08-31 19:07:57+02:00|2020-08-31 08:05:00+02:00|session|start|
wl log                  
       date      time category   type identifier
 2020-08-31  19:07:44  session   stop          -
 2020-08-31  08:05:00  session  start          -
```

Does this match the behavior you wanted to have?

**Comment by nils-braun** [comment]
I would love to have it sorted by log date, so that I can see what I did today - ordered by the time I did a task not by the time I logged it

**Comment by nils-braun** [comment]
Is the example you showed already implemented? Because for me it is currently not working like this

**Comment by dotcs** [comment]
Yes, it's implemeted and the behavior should match the one above. It has not been altered since some time now. So I'm wondering why this is not working for you.

Can you please showcase how it looks on your system?

**Comment by nils-braun** [comment]
Funnily, I can not reproduce it currently. Maybe I need to test it with new data. I think, we can close the issue now. Sorry for the noise
